const FONT =
  "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'SF Pro Text', system-ui, sans-serif";
const BLACK = "#000";
const GREY = "#86868b";
const LIGHT = "#f5f5f7";
const BORDER = "#d2d2d7";
const TEXT = "#1d1d1f";
const WHITE = "#fff";

const styles = {
  // Poll
  pollWrap: {
    minHeight: "100vh",
    background: WHITE,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 20px",
    fontFamily: FONT,
  },
  pollQuestion: {
    color: TEXT,
    fontSize: "clamp(20px, 5vw, 28px)",
    fontWeight: 600,
    textAlign: "center",
    marginBottom: 40,
    lineHeight: 1.3,
    letterSpacing: "-0.02em",
  },
  optionsWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    width: "100%",
    maxWidth: 440,
  },
  optionBtn: {
    background: WHITE,
    border: `1px solid ${BORDER}`,
    borderRadius: 12,
    padding: "18px 20px",
    cursor: "pointer",
    textAlign: "left",
    transition: "background 0.15s ease",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  optionBtnHover: {
    background: LIGHT,
    borderColor: BORDER,
    transform: "none",
  },
  beerName: {
    color: TEXT,
    fontSize: 17,
    fontWeight: 500,
    fontFamily: FONT,
  },
  beerStyle: {
    color: GREY,
    fontSize: 14,
    fontWeight: 400,
    fontFamily: FONT,
  },
  noneBtn: {
    background: "transparent",
    border: "none",
    borderRadius: 12,
    padding: "16px 20px",
    cursor: "pointer",
    color: GREY,
    fontSize: 15,
    textAlign: "center",
    transition: "background 0.15s ease",
    marginTop: 4,
    fontFamily: FONT,
  },
  closedText: {
    color: GREY,
    fontSize: 17,
    fontWeight: 400,
    fontFamily: FONT,
  },
  flashWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
  },
  flashIcon: { fontSize: 44 },
  flashText: {
    color: TEXT,
    fontSize: 20,
    fontWeight: 500,
    fontFamily: FONT,
  },
  loader: {
    width: 24,
    height: 24,
    border: `2.5px solid ${LIGHT}`,
    borderTopColor: GREY,
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },

  // Dashboard
  dashWrap: {
    minHeight: "100vh",
    background: WHITE,
    padding: "32px 20px",
    fontFamily: FONT,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  dashHeader: {
    width: "100%",
    maxWidth: 520,
    marginBottom: 32,
  },
  dashTitle: {
    color: TEXT,
    fontSize: 28,
    fontWeight: 700,
    marginBottom: 20,
    letterSpacing: "-0.02em",
  },
  tabRow: {
    display: "flex",
    gap: 0,
    borderBottom: `1px solid ${BORDER}`,
  },
  tab: {
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    padding: "10px 20px",
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s",
    fontFamily: FONT,
  },

  // Pin
  pinBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 20,
    marginTop: 100,
  },
  pinTitle: {
    color: TEXT,
    fontSize: 20,
    fontWeight: 600,
    fontFamily: FONT,
  },
  pinInput: {
    background: LIGHT,
    border: `1px solid ${BORDER}`,
    borderRadius: 12,
    padding: "14px 18px",
    color: TEXT,
    fontSize: 24,
    textAlign: "center",
    width: 180,
    letterSpacing: 8,
    outline: "none",
    transition: "border-color 0.2s",
    fontFamily: FONT,
  },
  pinSubmit: {
    background: BLACK,
    border: "none",
    borderRadius: 12,
    padding: "12px 36px",
    color: WHITE,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: FONT,
  },

  // Config
  configWrap: {
    width: "100%",
    maxWidth: 520,
    display: "flex",
    flexDirection: "column",
    gap: 28,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  label: {
    color: GREY,
    fontSize: 13,
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    fontFamily: FONT,
  },
  textInput: {
    background: LIGHT,
    border: `1px solid ${BORDER}`,
    borderRadius: 10,
    padding: "12px 14px",
    color: TEXT,
    fontSize: 16,
    outline: "none",
    fontFamily: FONT,
  },
  numBtn: {
    border: `1px solid ${BORDER}`,
    borderRadius: 10,
    padding: "10px 22px",
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
    background: LIGHT,
    color: TEXT,
    fontFamily: FONT,
  },
  beerList: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    background: BORDER,
    borderRadius: 12,
    overflow: "hidden",
  },
  beerRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: WHITE,
    padding: "14px 16px",
    borderLeft: "none",
  },
  beerRowName: { color: TEXT, fontSize: 15, fontWeight: 500, fontFamily: FONT },
  beerRowStyle: { color: GREY, fontSize: 13, fontFamily: FONT },
  removeBtn: {
    background: "none",
    border: "none",
    color: GREY,
    fontSize: 16,
    cursor: "pointer",
    padding: "4px 8px",
    fontFamily: FONT,
  },
  addRow: {
    display: "flex",
    gap: 8,
    marginTop: 8,
  },
  addBtn: {
    background: BLACK,
    border: "none",
    borderRadius: 10,
    width: 44,
    fontSize: 20,
    fontWeight: 600,
    color: WHITE,
    cursor: "pointer",
    flexShrink: 0,
    fontFamily: FONT,
  },
  saveBtn: {
    background: BLACK,
    border: "none",
    borderRadius: 12,
    padding: "12px 32px",
    color: WHITE,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: FONT,
  },
  liveBtn: {
    border: "none",
    borderRadius: 12,
    padding: "12px 28px",
    color: WHITE,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: FONT,
  },
  warn: {
    color: "#ff3b30",
    fontSize: 14,
    marginTop: 4,
    fontFamily: FONT,
  },

  // Results
  resultsWrap: {
    width: "100%",
    maxWidth: 520,
    display: "flex",
    flexDirection: "column",
    gap: 28,
  },
  heroBox: {
    background: LIGHT,
    border: "none",
    borderLeft: "none",
    borderRadius: 16,
    padding: "24px 20px",
    textAlign: "left",
  },
  heroLabel: {
    color: GREY,
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: 14,
    fontFamily: FONT,
  },
  heroName: {
    color: TEXT,
    fontSize: 22,
    fontWeight: 600,
    marginBottom: 4,
    letterSpacing: "-0.01em",
    fontFamily: FONT,
  },
  totalBox: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap",
  },
  totalNum: {
    color: TEXT,
    fontSize: 40,
    fontWeight: 700,
    letterSpacing: "-0.03em",
    fontFamily: FONT,
  },
  totalLabel: { color: GREY, fontSize: 16, fontFamily: FONT },
  confidenceNote: {
    color: GREY,
    fontSize: 13,
    width: "100%",
    marginTop: -4,
    fontFamily: FONT,
  },
  chartWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  barRow: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  barLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  barRank: {
    color: GREY,
    fontSize: 13,
    fontWeight: 500,
    minWidth: 28,
    fontFamily: FONT,
  },
  barName: { color: TEXT, fontSize: 15, fontWeight: 500, fontFamily: FONT },
  barTrack: {
    background: LIGHT,
    borderRadius: 6,
    height: 28,
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    borderRadius: 6,
    transition: "width 0.6s ease",
    minWidth: 4,
  },
  barStats: {
    display: "flex",
    gap: 12,
    alignItems: "center",
  },
  barPct: { color: TEXT, fontSize: 14, fontWeight: 600, fontFamily: FONT },
  barDetail: { color: GREY, fontSize: 12, fontFamily: FONT },

  dailyWrap: { marginTop: 4 },
  dailyTitle: {
    color: GREY,
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: 14,
    fontFamily: FONT,
  },
  dailyChart: {
    display: "flex",
    alignItems: "flex-end",
    gap: 4,
    height: 64,
  },
  dailyCol: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-end",
    height: "100%",
  },
  dailyBar: {
    width: "100%",
    background: TEXT,
    borderRadius: "4px 4px 0 0",
    minHeight: 2,
    transition: "height 0.4s ease",
  },
  dailyLabel: { color: GREY, fontSize: 10, marginTop: 4, fontFamily: FONT },
  qrHint: {
    background: LIGHT,
    borderRadius: 12,
    padding: "16px",
    textAlign: "center",
    border: "none",
  },
  qrText: { color: GREY, fontSize: 14, fontFamily: FONT },
  clearBtn: {
    background: "none",
    border: `1px solid ${BORDER}`,
    borderRadius: 10,
    padding: "10px 20px",
    color: GREY,
    fontSize: 14,
    cursor: "pointer",
    alignSelf: "flex-start",
    fontFamily: FONT,
  },
  backLink: {
    background: "none",
    border: "none",
    color: GREY,
    fontSize: 14,
    cursor: "pointer",
    marginTop: 40,
    padding: "8px 0",
    fontFamily: FONT,
    textDecoration: "none",
  },
};

export default styles;
