const FONT = "'IBM Plex Mono', 'SF Mono', 'Fira Code', 'Consolas', monospace";
const GREEN = "#4af626";
const BG = "#0c0c0c";
const BG2 = "#161616";
const DIM = "#555";
const TEXT = "#ccc";

const styles = {
  // Poll
  pollWrap: {
    minHeight: "100vh",
    background: BG,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 16px",
    fontFamily: FONT,
  },
  pollQuestion: {
    color: GREEN,
    fontSize: "clamp(16px, 4vw, 22px)",
    fontWeight: 400,
    textAlign: "center",
    marginBottom: 32,
    letterSpacing: "0em",
    lineHeight: 1.4,
  },
  optionsWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    width: "100%",
    maxWidth: 420,
  },
  optionBtn: {
    background: BG2,
    border: "1px solid #2a2a2a",
    borderRadius: 2,
    padding: "14px 16px",
    cursor: "pointer",
    textAlign: "left",
    transition: "all 0.1s ease",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  optionBtnHover: {
    background: "#1e1e1e",
    borderColor: GREEN,
    transform: "none",
  },
  beerName: {
    color: TEXT,
    fontSize: 14,
    fontWeight: 500,
    letterSpacing: "0em",
    fontFamily: FONT,
  },
  beerStyle: {
    color: DIM,
    fontSize: 12,
    fontWeight: 400,
    fontFamily: FONT,
  },
  noneBtn: {
    background: "transparent",
    border: "1px solid #222",
    borderRadius: 2,
    padding: "12px 16px",
    cursor: "pointer",
    color: DIM,
    fontSize: 13,
    textAlign: "center",
    transition: "all 0.1s ease",
    marginTop: 4,
    fontFamily: FONT,
  },
  closedText: {
    color: DIM,
    fontSize: 14,
    fontFamily: FONT,
  },
  flashWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
  },
  flashIcon: { fontSize: 36 },
  flashText: {
    color: GREEN,
    fontSize: 18,
    fontWeight: 400,
    letterSpacing: "0.05em",
    fontFamily: FONT,
  },
  loader: {
    width: 20,
    height: 20,
    border: "2px solid #222",
    borderTopColor: GREEN,
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },

  // Dashboard
  dashWrap: {
    minHeight: "100vh",
    background: BG,
    padding: "24px 16px",
    fontFamily: FONT,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  dashHeader: {
    width: "100%",
    maxWidth: 520,
    marginBottom: 24,
  },
  dashTitle: {
    color: GREEN,
    fontSize: 16,
    fontWeight: 400,
    marginBottom: 16,
    letterSpacing: "0.05em",
  },
  tabRow: {
    display: "flex",
    gap: 0,
    borderBottom: "1px solid #222",
  },
  tab: {
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 400,
    cursor: "pointer",
    transition: "all 0.1s",
    fontFamily: FONT,
  },

  // Pin
  pinBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    marginTop: 80,
  },
  pinTitle: {
    color: GREEN,
    fontSize: 14,
    fontWeight: 400,
    fontFamily: FONT,
  },
  pinInput: {
    background: BG2,
    border: "1px solid #333",
    borderRadius: 2,
    padding: "12px 16px",
    color: TEXT,
    fontSize: 20,
    textAlign: "center",
    width: 160,
    letterSpacing: 8,
    outline: "none",
    transition: "border-color 0.2s",
    fontFamily: FONT,
  },
  pinSubmit: {
    background: GREEN,
    border: "none",
    borderRadius: 2,
    padding: "10px 32px",
    color: "#000",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: FONT,
  },

  // Config
  configWrap: {
    width: "100%",
    maxWidth: 520,
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  label: {
    color: DIM,
    fontSize: 11,
    fontWeight: 400,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    fontFamily: FONT,
  },
  textInput: {
    background: BG2,
    border: "1px solid #2a2a2a",
    borderRadius: 2,
    padding: "10px 12px",
    color: TEXT,
    fontSize: 14,
    outline: "none",
    fontFamily: FONT,
  },
  numBtn: {
    border: "1px solid #2a2a2a",
    borderRadius: 2,
    padding: "8px 20px",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    background: BG2,
    color: TEXT,
    fontFamily: FONT,
  },
  beerList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  beerRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: BG2,
    borderRadius: 2,
    padding: "10px 12px",
    borderLeft: `2px solid ${DIM}`,
  },
  beerRowName: { color: TEXT, fontSize: 13, fontWeight: 500, fontFamily: FONT },
  beerRowStyle: { color: DIM, fontSize: 12, fontFamily: FONT },
  removeBtn: {
    background: "none",
    border: "none",
    color: "#444",
    fontSize: 14,
    cursor: "pointer",
    padding: "4px 8px",
    fontFamily: FONT,
  },
  addRow: {
    display: "flex",
    gap: 6,
    marginTop: 4,
  },
  addBtn: {
    background: GREEN,
    border: "none",
    borderRadius: 2,
    width: 40,
    fontSize: 18,
    fontWeight: 700,
    color: "#000",
    cursor: "pointer",
    flexShrink: 0,
    fontFamily: FONT,
  },
  saveBtn: {
    background: GREEN,
    border: "none",
    borderRadius: 2,
    padding: "10px 28px",
    color: "#000",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: FONT,
  },
  liveBtn: {
    border: "none",
    borderRadius: 2,
    padding: "10px 24px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: FONT,
  },
  warn: {
    color: "#e74c3c",
    fontSize: 12,
    marginTop: 8,
    fontFamily: FONT,
  },

  // Results
  resultsWrap: {
    width: "100%",
    maxWidth: 520,
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },
  heroBox: {
    background: BG2,
    border: "1px solid #1a3a10",
    borderLeft: `3px solid ${GREEN}`,
    borderRadius: 2,
    padding: "20px 16px",
    textAlign: "left",
  },
  heroLabel: {
    color: GREEN,
    fontSize: 11,
    fontWeight: 400,
    textTransform: "uppercase",
    letterSpacing: "0.15em",
    marginBottom: 12,
    fontFamily: FONT,
  },
  heroName: {
    color: TEXT,
    fontSize: 18,
    fontWeight: 500,
    marginBottom: 4,
    letterSpacing: "0em",
    fontFamily: FONT,
  },
  totalBox: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap",
  },
  totalNum: {
    color: GREEN,
    fontSize: 32,
    fontWeight: 400,
    letterSpacing: "-0.02em",
    fontFamily: FONT,
  },
  totalLabel: { color: DIM, fontSize: 14, fontFamily: FONT },
  confidenceNote: {
    color: "#444",
    fontSize: 11,
    width: "100%",
    marginTop: -4,
    fontFamily: FONT,
  },
  chartWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  barRow: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  barLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  barRank: { color: DIM, fontSize: 11, fontWeight: 400, minWidth: 24, fontFamily: FONT },
  barName: { color: TEXT, fontSize: 13, fontWeight: 400, fontFamily: FONT },
  barTrack: {
    background: BG2,
    borderRadius: 1,
    height: 22,
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    borderRadius: 1,
    transition: "width 0.6s ease",
    minWidth: 4,
  },
  barStats: {
    display: "flex",
    gap: 12,
    alignItems: "center",
  },
  barPct: { color: GREEN, fontSize: 13, fontWeight: 500, fontFamily: FONT },
  barDetail: { color: "#444", fontSize: 11, fontFamily: FONT },

  dailyWrap: { marginTop: 8 },
  dailyTitle: {
    color: DIM,
    fontSize: 11,
    fontWeight: 400,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    marginBottom: 12,
    fontFamily: FONT,
  },
  dailyChart: {
    display: "flex",
    alignItems: "flex-end",
    gap: 3,
    height: 60,
  },
  dailyCol: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-end",
    height: "100%",
  },
  dailyBar: {
    width: "100%",
    background: GREEN,
    borderRadius: "1px 1px 0 0",
    minHeight: 2,
    transition: "height 0.4s ease",
  },
  dailyLabel: { color: "#444", fontSize: 9, marginTop: 4, fontFamily: FONT },
  qrHint: {
    background: BG2,
    borderRadius: 2,
    padding: "14px",
    textAlign: "center",
    border: "1px solid #222",
  },
  qrText: { color: DIM, fontSize: 12, fontFamily: FONT },
  clearBtn: {
    background: "none",
    border: "1px solid #222",
    borderRadius: 2,
    padding: "8px 16px",
    color: DIM,
    fontSize: 12,
    cursor: "pointer",
    alignSelf: "flex-start",
    fontFamily: FONT,
  },
  backLink: {
    background: "none",
    border: "none",
    color: DIM,
    fontSize: 12,
    cursor: "pointer",
    marginTop: 32,
    padding: "8px 0",
    fontFamily: FONT,
  },
};

export default styles;
